# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Sep 21 12:10:22 PM EEST 2022
#
#/ usage: my-print-env:print [ --color_id_name <31>] [ --color_id_var <32>] [ --color_id_for_equals <0>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
  
    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --color_id_name) rerun_option_check $# $1; COLOR_ID_NAME=$2 ; shift 2 ;;
            --color_id_var) rerun_option_check $# $1; COLOR_ID_VAR=$2 ; shift 2 ;;
            --color_id_for_equals) rerun_option_check $# $1; COLOR_ID_FOR_EQUALS=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.
    [[ -z "$COLOR_ID_NAME" ]] && COLOR_ID_NAME="$(rerun_property_get $RERUN_MODULE_DIR/options/color_id_name DEFAULT)"
    [[ -z "$COLOR_ID_VAR" ]] && COLOR_ID_VAR="$(rerun_property_get $RERUN_MODULE_DIR/options/color_id_var DEFAULT)"
    [[ -z "$COLOR_ID_FOR_EQUALS" ]] && COLOR_ID_FOR_EQUALS="$(rerun_property_get $RERUN_MODULE_DIR/options/color_id_for_equals DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${COLOR_ID_NAME:=}
: ${COLOR_ID_VAR:=}
: ${COLOR_ID_FOR_EQUALS:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


